export const LOAD_CITIES = "LOAD_CITIES";
export const ADD_CITY = "ADD_CITY";
export const LOAD_GEO_LOCATION_SUCCESS = "LOAD_GEO_LOCATION_SUCCESS";
export const LOAD_WEATHER_DATA_SUCCESS = "LOAD_WEATHER_DATA_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";